spring:
  application:
    name: code-samples
  datasource:
    url: ${DEMO_DB_URL}
    username: ${DEMO_DB_USR}
    password: ${DEMO_DB_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,liveness,readiness
  endpoint:
    health:
      show-details: always
      enabled: true
      probes:
        enabled: true

dev:
  gabrielmumo:
    security:
      jwt-secret: ${JWT_SECRET}
      token-type: Bearer
      expiration-time: 70000
      refresh-times: 3